on:
  push:
    branches: [master, release-*]
    tags: ["*.*.*"]
  pull_request:
env:
  DOTNET_NOLOGO: true
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        job:
          - os: macos-10.15
            build: ./build.sh
            push: ""
          - os: ubuntu-18.04
            build: ./build.sh
            push: ./push.sh
          - os: windows-2019
            build: ./build.cmd
            push: ""
    name: ${{ matrix.job.os }}
    runs-on: ${{ matrix.job.os }}
    steps:
      - uses: actions/setup-dotnet@51f68377c181a79065c61bd492bd49be4575c439
        with:
          dotnet-version: "3.1.402"
      - run: dotnet --info
      - uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
        with:
          fetch-depth: 0
      - run: ${{ matrix.job.build }}
      - name: push
        if: matrix.job.push != ''
        env:
          MYGET_ADAMRALPH_CI_API_KEY: ${{ secrets.MYGET_ADAMRALPH_CI_API_KEY }}
        run: ${{ matrix.job.push }}
