on:
  push:
    branches: [master]
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: github/super-linter@v3
        env:
          FILTER_REGEX_EXCLUDE: ^\.\/LICENSE$|\w*\.sln$|\blog\.txt$
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
